### ISSUE TITLE
Не удается прошить приемник

### ISSUE THREAD

**Issue by i--storm** [night-ghost/CoolBeacon#1]
Пытаюсь прошить приемник Orange OpenLRS.
Прошил бутлоадер из ардуины. Скетчи из примеров Ардуино загружаются нормально.
Но ConfigTool говорит что Failed to Talk to Bootloader 
Пробовал скомпилировать проект в Ардуино
Тоже ошибка: OpenBeacon:482: error: 'Coord' was not declared in this scope

**Comment by night-ghost** [comment]
Маяк рассчитан на OptiBoot, так что для прошивки через Ардуино надо выбирать плату Arduino Genuino Uno. 

>Пробовал скомпилировать проект в Ардуино

У меня собирается без ошибок

**Comment by i--storm** [comment]
А под какой версией ардуины?

**Comment by night-ghost** [comment]
Пробовал от 1.6.6 и до 1.8.1
